name: Hello World

on: [pull_request]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "🎉 Hello, Team PR Raised"
